### ISSUE TITLE
Ensure we can run KI within a gradle project

### ISSUE THREAD

**Issue by tjerkw** [Kotlin/kotlin-interactive-shell#108]
A common use case is running a KI shell for the current project, to get all dependencies loaded up.

Something like this would be cool `./gradlew kiShell` to run the shell with all dependencies loaded.

In theory I could hack something together and generate some lines of `:dependsOn` by mapping the result of `./gradlew dependencies` and than invoking "ki", but this indeed feels like a hack. And it requires developers to install "ki" manually (its not part of the project). 

Is there a possibility to make KI a dependency of the project and run it within gradle?

**Comment by asm0dey** [comment]
Sorry, but I have no idea. But you definitely can add ki as a regular dependency, Anyways running it as a task in Gradle is not in a scope of this project.
