### ISSUE TITLE
Weird behavior with backslash in ki-shell

### ISSUE THREAD

**Issue by LaurentBerger** [Kotlin/kotlin-interactive-shell#111]
Hi,

configuration windows 10 x64 
ki-shell 0.4.5/1.6.10

I try this [example  ](https://kotlinlang.org/docs/basic-types.html#characters)in a script : it’s OK

```
c\:>kotlinc -script char_example.kts
a


?

C:\>
```

Now I try same code in ki-shell

```
[33] val aChar: Char = 'a'
[34] println(aChar)
a
[35] println('line 1:9 token recognition error at: '\'
\line 1:9 token recognition error at: '\'
'\n')  //prints an extra newline character
```
It seems that backslash character cannot be used in console

**Comment by asm0dey** [comment]
@ligee could you take a look pls?

**Comment by ligee** [comment]
@LaurentBerger, I'm not 100% sure that I understand, what you mean - the link to the "OK script" leads to some doc page, and the example contains improperly quoted string.
But I assume that you're using special characters incorrectly. According to Kotlin docs - https://kotlinlang.org/docs/basic-types.html#characters - the backslash is a special character, so to use it by itself, you need to escape it with another one - `'\\'` or `"\\"`.

**Comment by LaurentBerger** [comment]
First line type println("hello") and second line println("\ error

https://user-images.githubusercontent.com/3591626/176933814-ca13c816-b5a1-4525-8b27-e594f72d7ff4.mp4

**Comment by asm0dey** [comment]
@ligee here is the reproducer: https://asciinema.org/a/r6gQpn7ubTaTXPi8WpCywvA6N

**Comment by ligee** [comment]
Ok, got it. Looks like jline problem to investigate.

**Comment by LaurentBerger** [comment]
@ligee  Why do you [close issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/closing-an-issue)? Is it solved?

**Comment by ligee** [comment]
@LaurentBerger, yes. Actually, github closed it automatically when I mentioned it in the commit with the fix. You can see it linked to the close message.

**Comment by LaurentBerger** [comment]
I think that If I want the new version I have to compile myself. Is it right?

**Comment by LaurentBerger** [comment]
It works

```
ki-shell 0.5.2/1.7.0
type :h for help
[0] println("\nOK")

OK
```
