### ISSUE TITLE
Support for newer Kotlin versions?

### ISSUE THREAD

**Issue by oxisto** [Kotlin/kotlin-interactive-shell#128]
Hi!

We are using this project to have a small shell in our source code analysis project (https://github.com/Fraunhofer-AISEC/cpg) and it worked quite well! But recently, because of upgrades to the Kotlin version, the shell has stopped working altogether (see also https://github.com/Fraunhofer-AISEC/cpg/issues/1272):
```
ERROR Class 'de.fraunhofer.aisec.cpg.TranslationConfiguration' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.
```

Are there any plans to support newer Kotlin versions? I see that there was not much activity on this repo recently. Is this still something that the Kotlin team considers supporting?

BR,

Christian

**Comment by ligee** [comment]
Updated to 1.9.10
