### ISSUE TITLE
W: An illegal reflective access operation has occurred

### ISSUE THREAD

**Issue by theapache64** [Kotlin/kotlin-interactive-shell#56]
![image](https://user-images.githubusercontent.com/9678279/113300265-5e465600-931b-11eb-84df-adf9fbe88b05.png)

Is this expected?

**Comment by dodalovic** [comment]
Try using `jdk 8`

**Comment by abelkov** [comment]
The warning should go away when ki updates its Kotlin compiler to 1.5: https://youtrack.jetbrains.com/issue/KT-43520

**Comment by arynxd** [comment]
> The warning should go away when ki updates its Kotlin compiler to 1.5: 
is there any way to do this manually?

**Comment by khud** [comment]
I will fix it soon. If you use JDK 9+, the best way to walk it around is to use `--add-opens`:
```
java --add-opens java.base/java.util=ALL-UNNAMED -jar ${KI_SHELL} $@
```
