### ISSUE TITLE
Offer a homebrew installation option

### ISSUE THREAD

**Issue by kevincianfarini** [Kotlin/kotlin-interactive-shell#58]
It'd be great if users could have easy access to installation and updates with homebrew!

**Comment by SalvatoreT** [comment]
@asm0dey and @khud, I'm trying to add this project to Homebrew so folks can `brew install ki` for easier use.

The Homewbrew CI checks won't pass because the Maven Jar plugin (2.6) doesn't work on the Big Sur M1 instance. I've found that if I update the Maven Jar plugin to 3.2.0, everything goes great. If we want `ki` on Homebrew, we'll need to do the following.

1. Merge this PR to bump the Maven Jar plugin https://github.com/Kotlin/kotlin-interactive-shell/pull/64
2. Release a new version of kotlin-interactive shell (`v0.3.3` or something)
3. Update the Homebrew PR to use the new version https://github.com/Homebrew/homebrew-core/pull/74409
4. Shepherd the Homebrew PR through the review process

I can take care of 3 and 4 if y'all can help me on 1 and 2.

**Comment by SalvatoreT** [comment]
@asm0dey and @khud, can one of y'all please tag a new release? The Homebrew formula needs to pull from the canonical repository (this one) and can't use my fork as the base.

**Comment by khud** [comment]
We will do it soon. I need to fix a couple of things.

**Comment by SalvatoreT** [comment]
Roger that. Thank you!

**Comment by asm0dey** [comment]
Hi @SalvatoreT!

We've updated shell file and created new release with fixed command-line launcher. Feel free to update `jreleaser.toml` or update `ki` yourself!

**Comment by asm0dey** [comment]
We've provided our own formula in `jetbrains/utils` tap: https://github.com/JetBrains/homebrew-utils/blob/master/Formula/ki.rb

**Comment by SalvatoreT** [comment]
Hey @asm0dey, I'm glad y'all got something set up!

I am a bit frustrated that I spent time trying to add `ki` to `homebrew-core` if it was supposed to go into the JetBrains `homebrew-utils` project the whole time. If you would have told me at the start, I would have happily added it there instead.

**Comment by asm0dey** [comment]
@SalvatoreT no-no-no, it's definitely better to have it in the homebrew core! `homebrew-utils` is just a spare option in case if something will go wrong.

We will update it, but let's be honest: nobody knows about it. And of course, we will add `homebrew-core` to the README as installation option as soon as it will become available!

Thank you for your effort and we're waiting for your PR to be merged!

**Comment by kevincianfarini** [comment]
@SalvatoreT I greatly appreciate your efforts. Thank you.

**Comment by SalvatoreT** [comment]
> @SalvatoreT no-no-no, it's definitely better to have it in the homebrew core! `homebrew-utils` is just a spare option in case if something will go wrong.
> 
> We will update it, but let's be honest: nobody knows about it. And of course, we will add `homebrew-core` to the README as installation option as soon as it will become available!
> 
> Thank you for your effort and we're waiting for your PR to be merged!

Oh! Sorry, I misunderstood the intent of your earlier message. 😅 

I re-opened the `homebrew-core` PR, and we're back in business!

**Comment by asm0dey** [comment]
@SalvatoreT, I'm deeply sorry if my message looked rude or offensive to you. Please, excuse me for not being able to say things correctly. We highly appreciate your work and thank you again for all the effort you've made!

**Comment by asm0dey** [comment]
@SalvatoreT, I'm deeply sorry if my message looked rude or offensive to you. Please, excuse me for not being able to say things correctly. We highly appreciate your work and thank you again for all the effort you've made!

**Comment by SalvatoreT** [comment]
No, you didn't do anything wrong!

I should have asked if you wanted to keep the `homebrew-core` PR instead of assuming that you didn't! The fault was definitely on my end.

**Comment by asm0dey** [comment]
@SalvatoreT will it break the distribution if in next releases the root entry of a zip archive will be not 'ki', but 'ki-versionNumber'?

**Comment by SalvatoreT** [comment]
The Homebrew distribution is based off the `lib/ki-shell.jar` file ([source](https://github.com/Homebrew/homebrew-core/blob/4ebbc27b0825b9e059ac2789cd350ebcd2f74f81/Formula/ki.rb#L22-L23)). If needed, we can update that to point at something else. It shouldn't be too hard.

**Comment by SalvatoreT** [comment]
@asm0dey, I can update it if needed. Just let me know!

**Comment by asm0dey** [comment]
@SalvatoreT, thank you! Never mind, I've found a way not to change anything in a backward-incompatible way.
