### ISSUE TITLE
SDKMAN Installation option

### ISSUE THREAD

**Issue by MarioAriasC** [Kotlin/kotlin-interactive-shell#60]
SDKMAN is a very popular platform to distribute, install and update JVM related tools and SDK.

https://sdkman.io/

Can you provide integration with SDKMAN, please?

Thank you.

**Comment by tuppabox** [comment]
Almost I wanted to start the same again... but someone was faster.. ^^

Yes in my opinion its obligatory to use SDKMAN for installing. It is super easy and convenient. You get Kscript from there too. And Kotlin itself and Gradle of course...

**Comment by gildor** [comment]
Sdkman probably even more useful as part of sdkman rather than hombrew, because it allows to have multiple versions of it (and multiple Kotlin versions) at the same time

**Comment by asm0dey** [comment]
Hi folks, thank you for idea!

I've released the new version of ki and just applied to become an SDKMAN! vendor, so I hope it'll happen soon!

**Comment by gzsombor** [comment]
Any news from SDKMAN?

**Comment by asm0dey** [comment]
PR submitted: https://github.com/sdkman/sdkman-db-migrations/pull/575
