### ISSUE TITLE
"Unable to access jarfile" under Windows

### ISSUE THREAD

**Issue by helmbold** [Kotlin/kotlin-interactive-shell#61]
If I unpack the downloaded ki package, add the `bin` folder to the `PATH` and try to start it with `ki.bat` in cmd.exe or PowerShell, I get the following error:
```
C:\>ki.bat
Error: Unable to access jarfile C:\path\to\ki\bin\\..\lib\ki-shell-*.jar
```

If I change the the `.bat` file so that it includes a concrete path instead of a pattern, it works:

```
@echo off

set SCRIPT_PATH=%~dp0
set KI_SHELL=%SCRIPT_PATH%\..\lib\ki-shell-0.3.2.jar

java -jar %KI_SHELL% %*
```

**Comment by jas777** [comment]
Can confirm, `.sh` one works fine though

**Comment by evowizz** [comment]
Can confirm too.

I was able to fix it by modifying the .bat and creating the following script:

```bat
@echo off

set SCRIPT_PATH=%~dp0
set KI_SHELL_PATH=%SCRIPT_PATH%\..\lib\
set KI_SHELL_FORMAT=ki-shell-*.jar

for /r %KI_SHELL_PATH% %%i in (%KI_SHELL_FORMAT%) do (
    set KI_SHELL=%%~i
    GOTO found
)

@echo Unable to find Ki shell under %KI_SHELL_PATH%
exit /b

:found
java -jar %KI_SHELL% %*
```
