### ISSUE TITLE
ERROR Unable to initialize repl compiler:

### ISSUE THREAD

**Issue by sergey-morenets** [Kotlin/kotlin-interactive-shell#65]
Hi

I tried to use ki-shell 0.3.2 for Windows but encountered severe issues.
I started ki-shell, then typed "h" and got an exception (and got it again on every input). 
And I could't even quit the shell because Ctrl+C didn't work and help was unavailable.

```
type :h for help
[0] h
ERROR Unable to initialize repl compiler:
  ERROR java.lang.ExceptionInInitializerError: java.lang.ExceptionInInitializerError: java.lang.IllegalStateException: Unable to initialize repl compiler:
  ERROR java.lang.ExceptionInInitializerError: java.lang.ExceptionInInitializerError
```

**Comment by khud** [comment]
Hi, thank you.

What JDK version do you use?

**Comment by sergey-morenets** [comment]
> 
> 
> Hi, thank you.
> 
> What JDK version do you use?

JDK 16, build 16+36-2231

**Comment by khud** [comment]
I need some time for investigation. But you can use JDK8, it definitely works, or JDK11 with a small patch:
```
--add-opens java.base/java.util=ALL-UNNAMED
```

**Comment by sergey-morenets** [comment]
> 
> 
> I need some time for investigation. But you can use JDK8, it definitely works, or JDK11 with a small patch:
> 
> ```
> --add-opens java.base/java.util=ALL-UNNAMED
> ```

Thank you, I tried to add this flag for JDK 16:
`java --add-opens java.base/java.util=ALL-UNNAMED -jar ki-shell-0.3.2.jar `

Then original exception was gone but new error was reported:

```
type :h for help
[0] h
ERROR Unresolved reference: h (Line_1.kts:1:1)
```
