### ISSUE TITLE
Unable to execute kotlin-interactive-shell using a symbolic link to ki.sh

### ISSUE THREAD

**Issue by shoresea** [Kotlin/kotlin-interactive-shell#68]
When trying to install the `kotlin-interactive-shell` on Unix manually and creating a symbolic link to `bin/ki.sh`, the symbolic link fails to execute the `kotlin-interactive-shell` with an error message:

> Error: Unable to access jarfile /usr/local/bin/../lib/ki-shell-*.jar 

where  `/usr/local/bin` is the symbolic link path.

**Comment by khud** [comment]
Got it. Thank you. I will provide a fix asap.

**Comment by shoresea** [comment]
Thank you for providing the workaround. But, I already fixed it by setting `SCRIPT_DIR="$( dirname $(realpath "$0") )"` in `ki.sh` to get the real path of `ki.sh` instead of getting the real path of the symbolic link.

I am not sure if `realpath` is available in all UNIX based system, so didn't raise a PR with this fix.

**Comment by khud** [comment]
Thank you I will check this option on Linux. I believe it might work.

**Comment by khud** [comment]
Thank you. Merged.

**Comment by khud** [comment]
It's a bit tricky. It will not work on MacOS but it's better anyway. I need some time to fix it for MacOS too.

**Comment by shoresea** [comment]
It can work on macOS by installing `GNU coreutils` which provides `realpath`. A simple `brew install coreutils` should do the trick.
