### ISSUE TITLE
highlighting incorrect for if expression

### ISSUE THREAD

**Issue by sundeepbhatia** [Kotlin/kotlin-interactive-shell#79]
# highlighting incorrect for if expression 

```kotlin
fun max(a: Int, b: Int) = if (a > b) a else b
```

## Expected

R=red (keyword), Y=yellow (function), P=Pink (type) 

```text
RRR YYY(a: PPP, b: PPP) = RR (a > b) a RRRR b
```

## Actual

```text
RRR YYY(a: PPP, b: PPP) = RR Ra > b) a else b
```

## Version

- ki shell used `ki-shell-0.3.2-archive.zip`

- `kotlin -version`
```text
Kotlin version 1.4.10-release-411 (JRE 11.0.8+10)
```

- `java -version`

```text
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.8+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.8+10, mixed mode)
```
## Problems

1. open paren `(` after `if` gets highlighted as keyword
2. `else` is not highlighted as keyword

**Comment by bshtv** [comment]
Fixed https://github.com/Kotlin/kotlin-interactive-shell/pull/97
