### ISSUE TITLE
How to exit the interactive shell?

### ISSUE THREAD

**Issue by BWoodfork** [Kotlin/kotlin-interactive-shell#81]
Apologies, as I'm not seeing how to actually *quit* or terminate the interactive shell. Is this a feature that exists? If so, what are the instructions? I'd be interested in helping write something that allows a graceful exit from the shell or adding the instructions to do so to the ReadMe of the application, if this doesn't already exist. 

**Expected**
Some variation of `/exit` or `/quit` to quit the shell and return to your terminal prompt.

**Actual**
No command to exit the shell exists.

**Version**
Latest via Homebrew

**Comment by eihqnh** [comment]
Try to type :q or :quit

**Comment by BWoodfork** [comment]
> Try to type :q or :quit

Ah thanks! Adding this to the ReadMe.

**Comment by asm0dey** [comment]
Also <kbd>Ctrl</kbd>+<kbd>D</kbd> works
