### ISSUE TITLE
still uses Kotlin 1.4.32

### ISSUE THREAD

**Issue by nkiesel** [Kotlin/kotlin-interactive-shell#91]
This is now 2 major releases behind, and the only commit in the last 8 month was a small documentation improvement. Is this still alive?

**Comment by bshtv** [comment]
Hi, 1.6 up is on the radar.

**Comment by glockenstein** [comment]
I can compile it locally for 1.5.32, but 1.6.10 has issues.

**Comment by nkiesel** [comment]
I can build for 1.6.10 after adding `org.jetbrains.kotlinx:kotlinx-coroutines-core:1.6.0-RC2` dependency to `ki-shell/pom.xml`. I will create a merge request just to document that.

**Comment by nkiesel** [comment]
Attached diff instead (not worth creating a github clone for)
[0001-Upgraded-to-Kotlin-1.6.10.patch.txt](https://github.com/Kotlin/kotlin-interactive-shell/files/7738163/0001-Upgraded-to-Kotlin-1.6.10.patch.txt)

**Comment by bshtv** [comment]
https://github.com/Kotlin/kotlin-interactive-shell/pull/93

**Comment by asm0dey** [comment]
Fixed in 0.4.0
